# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"

# Add the following to activate the plugin
plugins:
  - jekyll-remote-theme
